In [3]:
# importing package using alias
import numpy as np

In [4]:
# Creating an array using a list
mList = [23, 45, 65, 87]
print(mList)
print(type(mList))

mArray = np.array(mList)
print(mArray)
print(type(mArray))

[23, 45, 65, 87]
<class 'list'>
[23 45 65 87]
<class 'numpy.ndarray'>


In [5]:
# Creating an array using a tuple
mTuple = (23, 45, 65, 87)
print(mTuple)
print(type(mTuple))

mArray = np.array(mTuple)
print(mArray)
print(type(mArray))

(23, 45, 65, 87)
<class 'tuple'>
[23 45 65 87]
<class 'numpy.ndarray'>


In [14]:
# 2-dimensional array
twoDArray = np.array([[23, 34, 54],[43, 65, 76]])
print(twoDArray)
print(f'Dimension of the array: {twoDArray.ndim}')

# Accessing values from a 2d array
print(twoDArray[0, 0])

# 0-dimensional array
zeroDArray = np.array(10)
print(zeroDArray)
print(f'Dimension of the array: {zeroDArray.ndim}')

[[23 34 54]
 [43 65 76]]
Dimension of the array: 2
23
10
Dimension of the array: 0
